interfaces:
  twentyFiveGigE 1/1:
    description: "TEMP_STORAGE_SEC"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged:
      - 203
      - 2305
      - 2306
      - 2307
    stp:
      disabled: true
  twentyFiveGigE 1/2:
    state: "down"
  twentyFiveGigE 1/3:
    state: "down"
  twentyFiveGigE 1/4:
    state: "down"
  twentyFiveGigE 1/5:
    state: "down"
  twentyFiveGigE 1/6:
    state: "down"
  twentyFiveGigE 1/7:
    state: "down"
  twentyFiveGigE 1/8:
    state: "down"
  twentyFiveGigE 1/9:
    state: "down"
  twentyFiveGigE 1/10:
    state: "down"
  twentyFiveGigE 1/11:
    state: "down"
  twentyFiveGigE 1/12:
    state: "down"
  twentyFiveGigE 1/13:
    state: "down"
  twentyFiveGigE 1/14:
    state: "down"
  twentyFiveGigE 1/15:
    state: "down"
  twentyFiveGigE 1/16:
    state: "down"
  twentyFiveGigE 1/17:
    state: "down"
  twentyFiveGigE 1/18:
    state: "down"
  twentyFiveGigE 1/19:
    state: "down"
  twentyFiveGigE 1/20:
    state: "down"
  twentyFiveGigE 1/21:
    state: "down"
  twentyFiveGigE 1/22:
    state: "down"
  twentyFiveGigE 1/23:
    description: "ResearchCephOSD_U03_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/24:
    description: "ResearchCephOSD_U03_2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 277
    tagged:
      - 201
      - 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/25:
    description: "ResearchCephOSD_U05_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/26:
    description: "ResearchCephOSD_U05_2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 277
    tagged:
      - 201
      - 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/27:
    description: "ResearchCephOSD_U07_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/28:
    description: "ResearchCephOSD_U07_2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 277
    tagged:
      - 201
      - 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/29:
    description: "ResearchCephOSD_U09_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/30:
    description: "ResearchCephOSD_U09_2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 277
    tagged:
      - 201
      - 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/31:
    description: "ResearchCephOSD_U11_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/32:
    description: "ResearchCephOSD_U11_2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 277
    tagged:
      - 201
      - 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/33:
    state: "down"
  twentyFiveGigE 1/34:
    state: "down"
  twentyFiveGigE 1/35:
    state: "down"
  twentyFiveGigE 1/36:
    state: "down"
  twentyFiveGigE 1/37:
    description: "ResearchCephMON_U13_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/38:
    description: "ResearchCephMON_U13_2"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/39:
    description: "ResearchCephMON_U15_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/40:
    description: "ResearchCephMON_U15_1"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/41:
    state: "down"
  twentyFiveGigE 1/42:
    state: "down"
  twentyFiveGigE 1/43:
    state: "down"
  twentyFiveGigE 1/44:
    state: "down"
  twentyFiveGigE 1/45:
    state: "down"
  twentyFiveGigE 1/46:
    state: "down"
  twentyFiveGigE 1/47:
    description: "MOC-R4PAC04-SW-MGMT Port 51"
    state: "up"
    mtu: 9216
  twentyFiveGigE 1/48:
    description: "MOC-R4PAC04-SW-MGMT Port 52"
    state: "up"
    mtu: 9216
  hundredGigE 1/49:
    state: "down"
  hundredGigE 1/50:
    state: "down"
  hundredGigE 1/51:
    state: "down"
  hundredGigE 1/52:
    state: "down"
  hundredGigE 1/53:
    description: "MOC-CORE-3 Uplink"
    state: "up"
    mtu: 9216
  hundredGigE 1/54:
    description: "MOC-CORE-4 Uplink"
    state: "up"
    mtu: 9216
  Port-channel 10:
    description: "MOC-CORE LAG"
    state: "up"
    tagged: "all"
    portmode: "trunk"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/53"
      - "hundredGigE 1/54"
  Port-channel 101:
    description: "MOC-R4PAC04-SW-MGMT Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "twentyFiveGigE 1/47"
      - "twentyFiveGigE 1/48"
    mlag: "Port-channel 101"
  Vlan 911:
    state: "up"
    ip4: "10.2.16.1/19"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.71/20"
